---
version: '3.7'

services:
  
  keenetic-grafana-monitoring:
    build: .
    container_name: keenetic-grafana-monitoring
   # environment:
   #   - TZ=Europe/Kiev
    volumes:
      - ./config/config.ini:/home/config/config.ini:ro
      - ./config/metrics.json:/home/config/metrics.json:ro
    restart: always

  # Influx 2.x

  influxdb:
    image: 'influxdb:2.1'
    volumes:
      - ./_data/influxdb:/var/lib/influxdb
    ports: 
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=keenetic
      - DOCKER_INFLUXDB_INIT_BUCKET=keenetic
      - DOCKER_INFLUXDB_INIT_RETENTION=52w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin_token
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password

  # Influx 1.x
  
  # influxdb:
  #   image: 'influxdb:1.8.1'
  #   volumes:
  #     - ./_data/influxdb:/var/lib/influxdb
  #   ports: 
  #     - 8086:8086
  #   environment:
  #     - INFLUXDB_DB=db0
  #     - INFLUXDB_HTTP_AUTH_ENABLED=true
  #     - INFLUXDB_ADMIN_USER=admin
  #     - INFLUXDB_ADMIN_PASSWORD=password
