{
 "title": "Keenetic",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "router",
    "label": "Router",
    "query": "SHOW TAG VALUES FROM \"system\" WITH KEY = \"router\""
   }
  ]
 },
 "panels": [
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "alias": "Ethernet Clients",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ip hotspot",
     "query": "SELECT last(\"speed\") as \"Ethernet\" FROM \"ip hotspot\" WHERE \"time\" > now() - 1m AND \"active\" = 1 AND $timeFilter AND \"router\" =~ /^(${router:regex})$/ GROUP BY \"mac\"",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "active", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Wi-Fi Clients",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"signal\") as \"Wi-Fi\" FROM \"ip hotspot\"  WHERE  \"time\" > now() - 1m AND \"active\" = 1 AND $timeFilter AND \"router\" =~ /^(${router:regex})$/ GROUP BY \"mac\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"uptime\") FROM \"system\" WHERE \"router\" =~ /^$router$/ LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "router", "operator": "=~", "value": "/^$router$/" }
     ]
    }
   ]
  },
  {
   "title": "Average system usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"memtotal\") - mean(\"memfree\") - mean(\"membuffers\") - mean(\"memcache\")) as \"RAM Usage\" FROM \"system\" WHERE $timeFilter AND \"router\" =~ /^(${router:regex})$/ GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpuload\") as \"CPU Usage\" FROM \"system\" WHERE $timeFilter AND \"router\" =~ /^(${router:regex})$/ GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "query": "SELECT(last(\"temperature\")) as \"Temperature\" FROM \"interface\" WHERE $timeFilter AND \"router\" =~ /^(${router:regex})$/ GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Internet status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "internet status",
     "query": "SELECT last(\"internet\") as \"Internet\", last(\"dns-accessible\") as \"DNS\", last(\"gateway-accessible\") as \"Gateway\" FROM \"internet status\" WHERE $timeFilter AND \"router\" =~ /^(${router:regex})$/",
     "select": [
      [
       { "params": [ "internet" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interfaces data transfered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Upload - $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "interface stat",
     "query": "SELECT non_negative_difference(mean(\"txbytes\")) FROM \"interface stat\" WHERE $timeFilter AND \"router\" =~ /^(${router:regex})$/ GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "txbytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Download - $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_difference(mean(\"rxbytes\")) FROM \"interface stat\" WHERE $timeFilter AND \"router\" =~ /^(${router:regex})$/ GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interfaces rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Upload - $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "interface stat",
     "query": "SELECT(mean(\"txspeed\")) FROM \"interface stat\" WHERE $timeFilter AND \"router\" =~ /^(${router:regex})$/ GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "txbytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Download - $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT(mean(\"rxspeed\")) FROM \"interface stat\" WHERE $timeFilter AND \"router\" =~ /^(${router:regex})$/ GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ip hotspot",
     "query": "SELECT non_negative_difference(mean(\"rxbytes\")) + non_negative_difference(mean(\"txbytes\")) FROM \"ip hotspot\" WHERE $timeFilter AND \"router\" =~ /^(${router:regex})$/ AND \"active\" = 1 GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "rxbytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ],
      [
       { "params": [ "txbytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "active", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Wi-Fi Clients signal level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "$tag_name [$tag_mode]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ip hotspot",
     "query": "SELECT mean(\"signal\") FROM \"ip hotspot\" WHERE $timeFilter AND \"router\" =~ /^(${router:regex})$/ AND \"active\" = 1 GROUP BY time($__interval), \"name\", \"mode\" fill(null)",
     "select": [
      [
       { "params": [ "signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wi-Fi Clients TX Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "alias": "$tag_name [$tag_mode]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ip hotspot",
     "query": "SELECT mean(\"txrate\") FROM \"ip hotspot\" WHERE $timeFilter AND \"router\" =~ /^(${router:regex})$/ AND \"active\" = 1 AND \"mode\" != \"\" GROUP BY time($__interval), \"name\", \"mode\" fill(null)",
     "select": [
      [
       { "params": [ "txrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "RAM Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"memtotal\") - mean(\"memfree\") FROM \"system\" WHERE $timeFilter AND \"router\" =~ /^(${router:regex})$/ GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpuload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free media space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "uuid" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "media",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_command",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "command" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "collector",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "interface-name" ], "type": "tag" },
      { "params": [ "address" ], "type": "tag" },
      { "params": [ "description" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "interface",
     "query": "SELECT last(\"state\") as \"State\" FROM \"interface\" WHERE $timeFilter AND \"router\" =~ /^(${router:regex})$/ AND \"description\" != '' GROUP BY \"description\"",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "processes",
     "query": "SELECT mean(\"cpu\") AS \"CPU\", mean(\"memory\") AS \"RAM\" FROM \"processes\" WHERE $timeFilter AND \"router\" =~ /^(${router:regex})$/ GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU" ], "type": "alias" }
      ],
      [
       { "params": [ "memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "RAM" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}